apiVersion: 1

datasources:
  - name: mysql-sda
    type: mysql
    access: proxy
    url: sda-mysql:3306
    database: sda_assignment3
    user: root
    secureJsonData:
      password: admin
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: true
    editable: true
